### ISSUE TITLE
Password-protected maps from webserver

### ISSUE THREAD

**Issue by ocrdu** [markoteittinen/custom-maps#18]
Hi,

I have made a qr-code with an url in the form of http://www.custommapsapp.com/qr?url=<actual-map-file-url>, but the actual-map-file-url points to a file in a password-protected webserver directory.

Am I correct in assuming this won't work? Any chance of it working in a future version?

Also, will there be a way of entering a .kmz file URL manually inside the app instead of scanning a QR-code or receiving a shared map?

Regards,

Oscar.

**Comment by markoteittinen** [comment]
You are correct. Custom Maps does not include capability to enter username and password to log into a website that requires logging in. And I don't think it is useful to add that capability to Custom Maps in the future.

But Custom Maps should be offered as an option for opening downloaded kmz-files. So if you create a qr-code for the direct web address, the browser should allow you to log in, and when the browser starts the download it should ask which app you want to open the file in. That list should include Custom Maps. If it doesn't, let me know. Also, if you try to open the downloaded kmz-file in Downloads directory using "Files" app, it should offer to open it with Custom Maps.

Since Custom Maps should be listed as an available app when one is opening kmz-files from browser or the file system, I don't see much benefit in adding an option of typing in a URL to download a map file.

**Comment by ocrdu** [comment]
OK, fair enough.
