### ISSUE TITLE
Enhancement request: allow using vector maps

### ISSUE THREAD

**Issue by GoogleCodeExporter** [markoteittinen/custom-maps#6]
```
The 12 Mpx limit is very strict. I often need to have lengthy maps (8-10 km 
long) with a descent resolution, this gives about 30-50x more pixels. Although 
those maps are 8-bit images of CAD drawings, and tend to be quite small for 
this magnitude, but still this is very CPU and memory consuming to process such 
bitmaps. And I have to split them to 12-Mpx chunks.

It would be great to be able to use vector images as maps. This way, I could 
export the map from my GIS to a supported vector format and use it as a whole.

Thank you for the great app!
```

Original issue reported on code.google.com by `mikekaga...@gmail.com` on 28 Aug 2013 at 12:44

**Comment by markoteittinen** [comment]
The maximum resolution shown in preferences is just a recommendation to avoid issues when Custom Maps is running. But basically Custom Maps attempts to load any image that the user selects, regardless its actual size. And Custom Maps is configured to use all the available memory Android OS provides each single application. Thus attempting to use a map image that is too large with cause Custom Maps to run out of memory, and crash. In some cases Custom Maps is able to detect the problem and gives an error message, but very often Android OS kills Custom Maps when it attempts to open a very large image. But so far each generation of Android OS has allowed each app to use more and more memory, so you can always try opening larger images when you change phone or update the OS.

Custom Maps doesn't support vector formats because Android OS does not contain APIs to render vector formats. PDF support has been added for Android devices running Lollipop or later (Lollipop added API for reading and rendering PDF files). But even in that case, Custom Maps converts the selected PDF page to a JPG image before using it as a map.
